// ==UserScript==
// @name        CountryChecker
// @updateURL https://maritoahike.neocities.org/legacy/userscript/CounryCheckerEnhanced.user.js
// @match		   https://admin.crimson.*.prd.maxbit.private/*
// @grant       none
// @version     1.52
// @author      Tishka, VIR and Mari Toahike


//whole  list of countries from Vir, much appreciated fam
// ==/UserScript==
if(window.location.href.match(/\/admin\/players\/[0-9]+/)){
    const countryID = document.querySelector(`.row.row-country td`).innerText;
    const countries = [
      {"name": "Afghanistan", "code": "AF", "color": "red"},
      {"name": "Åland Islands", "code": "AX", "color": "gray"},
      {"name": "Albania", "code": "AL", "color": "gray"},
      {"name": "Algeria", "code": "DZ", "color": "gray"},
      {"name": "American Samoa", "code": "AS", "color": "red"},
      {"name": "AndorrA", "code": "AD", "color": "gray"},
      {"name": "Angola", "code": "AO", "color": "gray"},
      {"name": "Anguilla", "code": "AI", "color": "gray"},
      {"name": "Antarctica", "code": "AQ", "color": "gray"},
      {"name": "Antigua and Barbuda", "code": "AG", "color": "gray"},
      {"name": "Argentina", "code": "AR", "color": "gray"},
      {"name": "Armenia", "code": "AM", "color": "gray"},
      {"name": "Aruba", "code": "AW", "color": "red"},
      {"name": "Australia", "code": "AU", "color": "gray"},
      {"name": "Austria", "code": "AT", "color": "green"},
      {"name": "Azerbaijan", "code": "AZ", "color": "gray"},
      {"name": "Bahamas", "code": "BS", "color": "gray"},
      {"name": "Bahrain", "code": "BH", "color": "gray"},
      {"name": "Bangladesh", "code": "BD", "color": "gray"},
      {"name": "Barbados", "code": "BB", "color": "gray"},
      {"name": "Belarus", "code": "BY", "color": "red"},
      {"name": "Bonaire, Sint Eustatius and Saba", "code": "BQ","color": "red"},
      {"name": "Belgium", "code": "BE", "color": "green"},
      {"name": "Belize", "code": "BZ", "color": "gray"},
      {"name": "Benin", "code": "BJ", "color": "gray"},
      {"name": "Bermuda", "code": "BM", "color": "gray"},
      {"name": "Bhutan", "code": "BT", "color": "gray"},
      {"name": "Bolivia", "code": "BO", "color": "gray"},
      {"name": "Bosnia and Herzegovina", "code": "BA", "color": "gray"},
      {"name": "Botswana", "code": "BW", "color": "gray"},
      {"name": "Bouvet Island", "code": "BV", "color": "gray"},
      {"name": "Brazil", "code": "BR", "color": "blue"},
      {"name": "British Indian Ocean Territory", "code": "IO", "color": "gray"},
      {"name": "Brunei Darussalam", "code": "BN", "color": "gray"},
      {"name": "Bulgaria", "code": "BG", "color": "gray"},
      {"name": "Burkina Faso", "code": "BF", "color": "gray"},
      {"name": "Burundi", "code": "BI", "color": "gray"},
      {"name": "Cambodia", "code": "KH", "color": "gray"},
      {"name": "Cameroon", "code": "CM", "color": "gray"},
      {"name": "Canada", "code": "CA", "color": "green"},
      {"name": "Cape Verde", "code": "CV", "color": "gray"},
      {"name": "Cayman Islands", "code": "KY", "color": "gray"},
      {"name": "Central African Republic", "code": "CF", "color": "red"},
      {"name": "Chad", "code": "TD", "color": "gray"},
      {"name": "Chile", "code": "CL", "color": "blue"},
      {"name": "China", "code": "CN", "color": "red"},
      {"name": "Christmas Island", "code": "CX", "color": "gray"},
      {"name": "Cocos (Keeling) Islands", "code": "CC", "color": "gray"},
      {"name": "Colombia", "code": "CO", "color": "gray"},
      {"name": "Comoros", "code": "KM", "color": "gray"},
      {"name": "Congo", "code": "CG", "color": "gray"},
      {"name": "Congo, The Democratic Republic of the", "code": "CD", "color": "gray"},
      {"name": "Cook Islands", "code": "CK", "color": "gray"},
      {"name": "Costa Rica", "code": "CR", "color": "gray"},
      {"name": "Cote D\"Ivoire", "code": "CI", "color": "red"},
      {"name": "Croatia", "code": "HR", "color": "gray"},
      {"name": "Cuba", "code": "CU", "color": "red"},
      {"name": "Cyprus", "code": "CY", "color": "red"},
      {"name": "Czech Republic", "code": "CZ", "color": "gray"},
      {"name": "Denmark", "code": "DK", "color": "blue"},
      {"name": "Djibouti", "code": "DJ", "color": "gray"},
      {"name": "Dominica", "code": "DM", "color": "gray"},
      {"name": "Dominican Republic", "code": "DO", "color": "gray"},
      {"name": "Ecuador", "code": "EC", "color": "blue"},
      {"name": "Curacao", "code": "CW", "color": "red"},
      {"name": "Egypt", "code": "EG", "color": "gray"},
      {"name": "El Salvador", "code": "SV", "color": "gray"},
      {"name": "Equatorial Guinea", "code": "GQ", "color": "gray"},
      {"name": "Eritrea", "code": "ER", "color": "gray"},
      {"name": "Estonia", "code": "EE", "color": "blue"},
      {"name": "Ethiopia", "code": "ET", "color": "red"},
      {"name": "Falkland Islands (Malvinas)", "code": "FK", "color": "gray"},
      {"name": "Faroe Islands", "code": "FO", "color": "gray"},
      {"name": "Fiji", "code": "FJ", "color": "gray"},
      {"name": "Finland", "code": "FI", "color": "gray"},
      {"name": "France", "code": "FR", "color": "red"},
      {"name": "French Guiana", "code": "GF", "color": "red"},
      {"name": "French Polynesia", "code": "PF", "color": "gray"},
      {"name": "French Southern Territories", "code": "TF", "color": "gray"},
      {"name": "Gabon", "code": "GA", "color": "gray"},
      {"name": "Gambia", "code": "GM", "color": "gray"},
      {"name": "Georgia", "code": "GE", "color": "gray"},
      {"name": "Germany", "code": "DE", "color": "green"},
      {"name": "Ghana", "code": "GH", "color": "gray"},
      {"name": "Gibraltar", "code": "GI", "color": "gray"},
      {"name": "Greece", "code": "GR", "color": "gray"},
      {"name": "Greenland", "code": "GL", "color": "red"},
      {"name": "Grenada", "code": "GD", "color": "gray"},
      {"name": "Guadeloupe", "code": "GP", "color": "red"},
      {"name": "Guam", "code": "GU", "color": "red"},
      {"name": "Guatemala", "code": "GT", "color": "gray"},
      {"name": "Guernsey", "code": "GG", "color": "gray"},
      {"name": "Guinea", "code": "GN", "color": "gray"},
      {"name": "Guinea-Bissau", "code": "GW", "color": "gray"},
      {"name": "Guyana", "code": "GY", "color": "gray"},
      {"name": "Haiti", "code": "HT", "color": "gray"},
      {"name": "Heard Island and Mcdonald Islands", "code": "HM", "color": "gray"},
      {"name": "Holy See (Vatican City State)", "code": "VA", "color": "gray"},
      {"name": "Honduras", "code": "HN", "color": "gray"},
      {"name": "Hong Kong", "code": "HK", "color": "gray"},
      {"name": "Hungary", "code": "HU", "color": "green"},
      {"name": "Iceland", "code": "IS", "color": "gray"},
      {"name": "India", "code": "IN", "color": "blue"},
      {"name": "Indonesia", "code": "ID", "color": "gray"},
      {"name": "Iran, Islamic Republic Of", "code": "IR", "color": "red"},
      {"name": "Iraq", "code": "IQ", "color": "red"},
      {"name": "Ireland", "code": "IE", "color": "gray"},
      {"name": "Isle of Man", "code": "IM", "color": "gray"},
      {"name": "Israel", "code": "IL", "color": "red"},
      {"name": "Italy", "code": "IT", "color": "blue"},
      {"name": "Jamaica", "code": "JM", "color": "gray"},
      {"name": "Japan", "code": "JP", "color": "blue"},
      {"name": "Jersey", "code": "JE", "color": "gray"},
      {"name": "Jordan", "code": "JO", "color": "red"},
      {"name": "Kazakhstan", "code": "KZ", "color": "#d99866"},
      {"name": "Kenya", "code": "KE", "color": "gray"},
      {"name": "Kiribati", "code": "KI", "color": "gray"},
      {"name": "Korea, Democratic People\"S Republic of", "code": "KP", "color": "red"},
      {"name": "Korea, Republic of", "code": "KR", "color": "gray"},
      {"name": "Kuwait", "code": "KW", "color": "gray"},
      {"name": "Kyrgyzstan", "code": "KG", "color": "gray"},
      {"name": "Lao People\"S Democratic Republic", "code": "LA", "color": "gray"},
      {"name": "Latvia", "code": "LV", "color": "blue"},
      {"name": "Lebanon", "code": "LB", "color": "red"},
      {"name": "Lesotho", "code": "LS", "color": "gray"},
      {"name": "Liberia", "code": "LR", "color": "gray"},
      {"name": "Libyan Arab Jamahiriya", "code": "LY", "color": "red"},
      {"name": "Liechtenstein", "code": "LI", "color": "gray"},
      {"name": "Lithuania", "code": "LT", "color": "blue"},
      {"name": "Luxembourg", "code": "LU", "color": "green"},
      {"name": "Macao", "code": "MO", "color": "red"},
      {"name": "Macedonia, The Former Yugoslav Republic of", "code": "MK", "color": "gray"},
      {"name": "Madagascar", "code": "MG", "color": "gray"},
      {"name": "Saint Martin (French)", "code": "MF", "color": "red"},
      {"name": "Malawi", "code": "MW", "color": "gray"},
      {"name": "Malaysia", "code": "MY", "color": "gray"},
      {"name": "Maldives", "code": "MV", "color": "gray"},
      {"name": "Mali", "code": "ML", "color": "red"},
      {"name": "Malta", "code": "MT", "color": "red"},
      {"name": "Marshall Islands", "code": "MH", "color": "gray"},
      {"name": "Martinique", "code": "MQ", "color": "red"},
      {"name": "Mauritania", "code": "MR", "color": "gray"},
      {"name": "Mauritius", "code": "MU", "color": "gray"},
      {"name": "Mayotte", "code": "YT", "color": "red"},
      {"name": "Mexico", "code": "MX", "color": "blue"},
      {"name": "Micronesia, Federated States of", "code": "FM", "color": "gray"},
      {"name": "Moldova, Republic of", "code": "MD", "color": "gray"},
      {"name": "Monaco", "code": "MC", "color": "gray"},
      {"name": "Mongolia", "code": "MN", "color": "gray"},
      {"name": "Montserrat", "code": "MS", "color": "gray"},
      {"name": "Morocco", "code": "MA", "color": "gray"},
      {"name": "Mozambique", "code": "MZ", "color": "gray"},
      {"name": "Myanmar", "code": "MM", "color": "red"},
      {"name": "Namibia", "code": "NA", "color": "gray"},
      {"name": "Nauru", "code": "NR", "color": "gray"},
      {"name": "Nepal", "code": "NP", "color": "gray"},
      {"name": "Netherlands", "code": "NL", "color": "red"},
      {"name": "Netherlands Antilles", "code": "AN", "color": "gray"},
      {"name": "New Caledonia", "code": "NC", "color": "gray"},
      {"name": "New Zealand", "code": "NZ", "color": "green"},
      {"name": "Nicaragua", "code": "NI", "color": "gray"},
      {"name": "Niger", "code": "NE", "color": "gray"},
      {"name": "Nigeria", "code": "NG", "color": "gray"},
      {"name": "Niue", "code": "NU", "color": "gray"},
      {"name": "Norfolk Island", "code": "NF", "color": "gray"},
      {"name": "Northern Mariana Islands", "code": "MP", "color": "gray"},
      {"name": "Norway", "code": "NO", "color": "gray"},
      {"name": "Oman", "code": "OM", "color": "red"},
      {"name": "Pakistan", "code": "PK", "color": "red"},
      {"name": "Palau", "code": "PW", "color": "gray"},
      {"name": "Palestinian Territory, Occupied", "code": "PS", "color": "gray"},
      {"name": "Panama", "code": "PA", "color": "gray"},
      {"name": "Papua New Guinea", "code": "PG", "color": "gray"},
      {"name": "Paraguay", "code": "PY", "color": "gray"},
      {"name": "Peru", "code": "PE", "color": "blue"},
      {"name": "Philippines", "code": "PH", "color": "gray"},
      {"name": "Pitcairn", "code": "PN", "color": "gray"},
      {"name": "Poland", "code": "PL", "color": "blue"},
      {"name": "Portugal", "code": "PT", "color": "blue"},
      {"name": "Puerto Rico", "code": "PR", "color": "red"},
      {"name": "Qatar", "code": "QA", "color": "gray"},
      {"name": "Reunion", "code": "RE", "color": "red"},
      {"name": "Romania", "code": "RO", "color": "gray"},
      {"name": "Russian Federation", "code": "RU", "color": "#d99866"},
      {"name": "RWANDA", "code": "RW", "color": "gray"},
      {"name": "Saint Helena", "code": "SH", "color": "gray"},
      {"name": "Saint Kitts and Nevis", "code": "KN", "color": "gray"},
      {"name": "Saint Lucia", "code": "LC", "color": "gray"},
      {"name": "Saint Pierre and Miquelon", "code": "PM", "color": "gray"},
      {"name": "Saint Vincent and the Grenadines", "code": "VC", "color": "gray"},
      {"name": "Samoa", "code": "WS", "color": "gray"},
      {"name": "San Marino", "code": "SM", "color": "gray"},
      {"name": "Sao Tome and Principe", "code": "ST", "color": "gray"},
      {"name": "Saudi Arabia", "code": "SA", "color": "gray"},
      {"name": "Senegal", "code": "SN", "color": "gray"},
      {"name": "Serbia and Montenegro", "code": "CS", "color": "gray"},
      {"name": "Serbia", "code": "RS", "color": "gray"},
      {"name": "Seychelles", "code": "SC", "color": "gray"},
      {"name": "Sierra Leone", "code": "SL", "color": "gray"},
      {"name": "Singapore", "code": "SG", "color": "gray"},
      {"name": "Slovakia", "code": "SK", "color": "red"},
      {"name": "Slovenia", "code": "SI", "color": "gray"},
      {"name": "Solomon Islands", "code": "SB", "color": "gray"},
      {"name": "Somalia", "code": "SO", "color": "red"},
      {"name": "South Africa", "code": "ZA", "color": "gray"},
      {"name": "South Georgia and the South Sandwich Islands", "code": "GS", "color": "gray"},
      {"name": "Spain", "code": "ES", "color": "red"},
      {"name": "Sri Lanka", "code": "LK", "color": "gray"},
      {"name": "Sudan", "code": "SD", "color": "red"},
      {"name": "Suriname", "code": "SR", "color": "gray"},
      {"name": "Svalbard and Jan Mayen", "code": "SJ", "color": "gray"},
      {"name": "Swaziland", "code": "SZ", "color": "gray"},
      {"name": "Sweden", "code": "SE", "color": "green"},
      {"name": "Switzerland", "code": "CH", "color": "green"},
      {"name": "Syrian Arab Republic", "code": "SY", "color": "red"},
      {"name": "Taiwan", "code": "TW", "color": "gray"},
      {"name": "Tajikistan", "code": "TJ", "color": "gray"},
      {"name": "Tanzania, United Republic of", "code": "TZ", "color": "gray"},
      {"name": "Thailand", "code": "TH", "color": "gray"},
      {"name": "Timor-Leste", "code": "TL", "color": "gray"},
      {"name": "Togo", "code": "TG", "color": "gray"},
      {"name": "Tokelau", "code": "TK", "color": "gray"},
      {"name": "Tonga", "code": "TO", "color": "gray"},
      {"name": "Trinidad and Tobago", "code": "TT", "color": "gray"},
      {"name": "Tunisia", "code": "TN", "color": "gray"},
      {"name": "Turkey", "code": "TR", "color": "blue"},
      {"name": "Turkmenistan", "code": "TM", "color": "gray"},
      {"name": "Turks and Caicos Islands", "code": "TC", "color": "gray"},
      {"name": "Tuvalu", "code": "TV", "color": "gray"},
      {"name": "Uganda", "code": "UG", "color": "gray"},
      {"name": "Ukraine", "code": "UA", "color": "#d99866"},
      {"name": "United Arab Emirates", "code": "AE", "color": "red"},
      {"name": "United Kingdom", "code": "GB", "color": "red"},
      {"name": "United States", "code": "US", "color": "red"},
      {"name": "United States Minor Outlying Islands", "code": "UM", "color": "red"},
      {"name": "Uruguay", "code": "UY", "color": "gray"},
      {"name": "Uzbekistan", "code": "UZ", "color": "gray"},
      {"name": "Vanuatu", "code": "VU", "color": "gray"},
      {"name": "Venezuela", "code": "VE", "color": "gray"},
      {"name": "Viet Nam", "code": "VN", "color": "gray"},
      {"name": "Virgin Islands, British", "code": "VG", "color": "gray"},
      {"name": "Virgin Islands, U.S.", "code": "VI", "color": "red"},
      {"name": "Wallis and Futuna", "code": "WF", "color": "gray"},
      {"name": "Western Sahara", "code": "EH", "color": "gray"},
      {"name": "Yemen", "code": "YE", "color": "red"},
      {"name": "Zambia", "code": "ZM", "color": "gray"},
      {"name": "Zimbabwe", "code": "ZW", "color": "red"}
  ];

    for(let curCountry of countries)
      {
        if(countryID == curCountry.code)
        {
          let setColor=curCountry.color;
          if(((curCountry.code=="LT") ||(curCountry.code=="PT") ||(curCountry.code=="KP"))&&(window.location.href.match("volna")))
            {
              setColor="red";
            };
          if((curCountry.code=="LT")&&(window.location.href.match("izzi")))
            {
              setColor="red";
            };
          let regdate= document.getElementsByClassName("row row-created_at")[0].children[1].innerText.split(" ")[0];
          document.getElementById("page_title").innerHTML += `<br><b style="color:${setColor}"> ${curCountry.name}</b><span style="font-size:16px; text-align:top;">       зарегистрирован: ${regdate}`;
        }
      }
}